server.port= 8080
#now eureka and gateway can indetify them
spring.application.name=gateway-service
spring.config.import=optional:configserver:http://localhost:8888
#iska kaam sirf itna hai ki ye config server se connect ho sake\
#GitHub Repo (online-store-config): Saari real routing logic aur rules yahan rahenge (gateway-service.yml).

