server.port=8761
#now eureka and gateway can indetify them
spring.application.name=registry-service

# tell Eureka Server not to register with or fetch from itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false